src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name_produit;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $marque_produit;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity_produit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNameProduit(): ?string
    {
        return $this->name_produit;
    }

    public function setNameProduit(string $name_produit): self
    {
        $this->name_produit = $name_produit;

        return $this;
    }

    public function getMarqueProduit(): ?string
    {
        return $this->marque_produit;
    }

    public function setMarqueProduit(string $marque_produit): self
    {
        $this->marque_produit = $marque_produit;

        return $this;
    }

    public function getQuantityProduit(): ?int
    {
        return $this->quantity_produit;
    }

    public function setQuantityProduit(int $quantity_produit): self
    {
        $this->quantity_produit = $quantity_produit;

        return $this;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name_produit')
            ->add('marque_produit')
            ->add('quantity_produit')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ProduitController extends AbstractController
{
    /**
     * @Route("/admin/produit/", name="produit_index", methods={"GET"})
     */
    public function index(ProduitRepository $produitRepository): Response
    {
        return $this->render('produit/index.html.twig', [
            'produits' => $produitRepository->findAll(),
        ]);
    }
    /**
     * @Route("/rest/produit/", name="rest_produit_index", methods={"GET"})
     */
    public function rest_index(ProduitRepository $produitRepository): Response
    {
        return $this->json($produitRepository->findAll());
    }
    /**
     * @Route("/admin/produit/new", name="produit_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }


    /**
     * @Route("/rest/produit/new", name="produit_new", methods={"GET", "POST"})
     */
    public function rest_new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produit();
        //remplir
        $produit->setNameProduit($request->query->get('nom'));
        $produit->setMarqueProduit($request->query->get('marque'));
        $produit->setQuantityProduit($request->query->get('quantity'));
        $entityManager->persist($produit);
        $entityManager->flush();

        return $this->json(['status' => 200, 'message' => "Produit ajouté avec succés"]);
    }

    /**
     * @Route("/admin/produit/view/{id}", name="produit_show", methods={"GET"})
     */
    public function show(Produit $produit): Response
    {
        return $this->render('produit/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    /**
     * @Route("/rest/produit/view/{id}", name="rest_produit_show", methods={"GET"})
     */
    public function rest_show(Produit $produit): Response
    {
        return $this->json($produit);
    }

    /**
     * @Route("/admin/produit/edit/{id}", name="produit_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('produit/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

        /**
     * @Route("/rest/produit/edit/{id}", name="produit_edit", methods={"GET", "POST"})
     */
    public function rest_edit(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        //remplir
        $produit->setNameProduit($request->query->get('nom'));
        $produit->setMarqueProduit($request->query->get('marque'));
        $produit->setQuantityProduit($request->query->get('quantity'));
        $entityManager->persist($produit);
        $entityManager->flush();

        return $this->json(['status' => 200, 'message' => "Produit modifié avec succés", 'data'=>$produit]);
    }

    /**
     * @Route("/admin/produit/delete/{id}", name="produit_delete", methods={"POST"})
     */
    public function delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $produit->getId(), $request->request->get('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/rest/produit/delete/{id}", name="rest_produit_delete", methods={"GET","POST"})
     */
    public function rest_delete(Request $request, Produit $produit, EntityManagerInterface $entityManager): Response
    {
        // $entityManager->$this->getdoctrine()->getManager();

        $entityManager->remove($produit);
        $entityManager->flush();

        return $this->json(['status' => 200, 'message' => "Produit supprimé avec succés"]);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Delete</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}
    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    <h1>Produit index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name_produit</th>
                <th>Marque_produit</th>
                <th>Quantity_produit</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.id }}</td>
                <td>{{ produit.nameProduit }}</td>
                <td>{{ produit.marqueProduit }}</td>
                <td>{{ produit.quantityProduit }}</td>
                <td>
                    <a href="{{ path('produit_show', {'id': produit.id}) }}">show</a>
                    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('produit_new') }}">Create new</a>
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}
    <h1>Create new Produit</h1>

    {{ include('produit/_form.html.twig') }}

    <a href="{{ path('produit_index') }}">back to list</a>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit{% endblock %}

{% block body %}
    <h1>Produit</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ produit.id }}</td>
            </tr>
            <tr>
                <th>Name_produit</th>
                <td>{{ produit.nameProduit }}</td>
            </tr>
            <tr>
                <th>Marque_produit</th>
                <td>{{ produit.marqueProduit }}</td>
            </tr>
            <tr>
                <th>Quantity_produit</th>
                <td>{{ produit.quantityProduit }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('produit_index') }}">back to list</a>

    <a href="{{ path('produit_edit', {'id': produit.id}) }}">edit</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}